<!-- BEGIN BASE JS -->
<?php Tag::js('../assets/vendor/jquery/jquery.min') ?>
<?php Tag::js('../assets/vendor/popper.js/umd/popper.min') ?>
<?php Tag::js('../assets/vendor/bootstrap/js/bootstrap.min') ?>


<!-- BEGIN PLUGINS JS -->
<?php Tag::js('../assets/vendor/pace-progress/pace.min') ?>
<?php Tag::js('../assets/vendor/stacked-menu/js/stacked-menu.min') ?>
<?php Tag::js('../assets/vendor/perfect-scrollbar/perfect-scrollbar.min') ?>
<?php Tag::js('../assets/javascript/theme.min') ?>



{% if page.pluginsJs %}
{% for js in page.pluginsJs %}
<script src="assets/vendor/{{js}}"></script>
{% endfor %}
{% endif %}
<!-- END PLUGINS JS -->




<?php 
$dir = 'assets/javascript/';
foreach( new DirectoryIterator($dir) as $fileI ) : ?>
  <link rel="stylesheet" 
  href="assets/javascript//<?php echo basename($fileI->getFilename())?>">

<?php endforeach ?>