<!-- BEGIN BASE JS -->
<script src="assets/vendor/jquery/jquery.min.js"></script>
<script src="assets/vendor/popper.js/umd/popper.min.js"></script>
<script src="assets/vendor/bootstrap/js/bootstrap.min.js"></script>
<!-- END BASE JS -->

<!-- BEGIN PLUGINS JS -->
<script src="assets/vendor/pace-progress/pace.min.js"></script>
<script src="assets/vendor/stacked-menu/js/stacked-menu.min.js"></script>
<script src="assets/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
{% if page.pluginsJs %}
{% for js in page.pluginsJs %}
<script src="assets/vendor/{{js}}"></script>
{% endfor %}
{% endif %}
<!-- END PLUGINS JS -->

<!-- BEGIN THEME JS -->
<script src="assets/javascript/theme.min.js"></script>
<!-- END THEME JS -->



<?php 
$dir = 'assets/javascript/';
foreach( new DirectoryIterator($dir) as $fileI ) : ?>
  <link rel="stylesheet" 
  href="assets/javascript//<?php echo basename($fileI->getFilename())?>">

<?php endforeach ?>