
<div class="m-5 text-white">
<h1>Bienvenido Index</h1>

<p>
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
    Dicta reprehenderit dolor exercitationem mollitia repellat debitis ratione. 
    Ut id, reprehenderit tempora deserunt minus quidem, consequuntur error molestias magni, f
    uga similique quos?

    Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Facilis sunt magni sed, officia minima deleniti dicta obcaecati dolore sapiente corrupti 
    animi similique repellat aspernatur quidem vel provident quasi saepe. Quasi.
</p>
</div>
