<!-- {% assign actives = page.active | split: "." %} -->
<!-- .menu-item -->


<!-- {% if levelMenu.id == actives[0] %} --> 
<?php if ($levelMenu["id"]=="dashboard") : ?>
<li class="menu-item has-active<?php if (isset($levelMenu["isSlim"])) : ?> menu-item-slim<?php endif ?><?php if (isset($levelMenu["childs"])) : ?> has-child<?php endif ?>">
<?php else : ?>
<li class="menu-item<?php if (isset($levelMenu["isSlim"])) : ?> menu-item-slim<?php endif ?><?php if (isset($levelMenu["childs"])) : ?> has-child<?php endif ?>">
<?php endif ?>

  <a href="<?= $levelMenu["link"] ?>" class="menu-link">
   
    <?php if (isset($levelMenu["icon"])) : ?> 
    <span class="menu-icon <?= $levelMenu["icon"] ?>"></span>
    <?php endif ?>

    <?php if (isset($levelMenu["text"])) : ?>
    <span class="menu-text"><?= $levelMenu["text"] ?></span>
    <?php endif ?>

    <?php if (isset($levelMenu["indicator"])) : ?>    
    <span class="<?= $levelMenu["indicatorClasses"] ?>">><?= $levelMenu["indicator"] ?></span>
    <?php endif ?>
  </a>

  <?php 
    if (isset($levelMenu["childs"]))
       View::partial('snippets/aside/menu-item', false, array('childs' => $levelMenu["childs"]));
  ?>
  

</li>
<!-- /.menu-item -->