<!-- {% assign actives = page.active | split: "." %} -->
<!-- child menu -->
<ul class="menu">
  <?php foreach ($childs as $menuItem) : ?>

  <!-- {% if menuItem.id == actives[1] %} -->
  <?php if ($menuItem["id"]=="clients") : ?>
    <li class="menu-item has-active<?php if (isset($menuItem["childs"])) : ?> has-child<?php endif ?>">
  <?php else : ?>
    <li class="menu-item<?php if (isset($menuItem["childs"])) : ?> has-child<?php endif ?>">
  <?php endif ?>
    <a href="<?= $menuItem["link"] ?>" class="menu-link">
     
      <?= $menuItem["text"] ?>
      <?php if (isset($menuItem["indicator"])) : ?>
      <span class="<?= $menuItem["indicatorClasses"] ?>"> <?= $menuItem["indicator"] ?></span>
      <?php endif ?>
    </a>
    

     <?php 
      if (isset($menuItem["childs"])) 
        View::partial('snippets/aside/child-item', false, array('childs' => $menuItem["childs"]));
     ?>
  </li>
  <?php endforeach ?>
</ul>
<!-- /child menu -->